### ISSUE TITLE
Some maps stuck at loading in Chrome

### ISSUE THREAD

**Issue by matikin9** [codeforamerica/click_that_hood#284]
Some of the maps get stuck on the loading bar when I try to load them in Chrome (e.g. Los Angeles County, Los Angeles City).

**Comment by k-nut** [comment]
This seems to be because of an `Uncaught TypeError: Cannot read property 'numberOfItems' of undefined` in [line 126 in script.js](https://github.com/codeforamerica/click_that_hood/blob/master/public/js/scripts.js#L126)

**Comment by mwichary** [comment]
Thanks, it’s because of the deprecated SVGPathSeg. I added a (backwards) polyfill as a temporary measure. Can you try now?

**Comment by matikin9** [comment]
Awesome - works great now, thanks!
